// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Migrations;

#nullable disable

namespace Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240127063442_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Migrations.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Attempts = 0,
                            Login = "test_login",
                            PasswordHash = "my_passhash",
                            UserId = -5
                        },
                        new
                        {
                            Id = -2,
                            Attempts = 0,
                            Login = "test_login2",
                            PasswordHash = "my_testPassHash",
                            UserId = -5
                        });
                });

            modelBuilder.Entity("Migrations.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("surname");

                    b.Property<int?>("UserAddressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAddressId")
                        .IsUnique()
                        .HasFilter("[UserAddressId] IS NOT NULL");

                    b.ToTable("user_table", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            FirstName = "Phillip",
                            LastName = "Ondricka"
                        },
                        new
                        {
                            Id = -2,
                            FirstName = "Joey",
                            LastName = "Dietrich"
                        },
                        new
                        {
                            Id = -3,
                            FirstName = "Emilio",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            Id = -4,
                            FirstName = "Jaime",
                            LastName = "Heidenreich"
                        },
                        new
                        {
                            Id = -5,
                            FirstName = "Dean",
                            LastName = "Schowalter",
                            UserAddressId = -1
                        },
                        new
                        {
                            Id = -6,
                            FirstName = "Marie",
                            LastName = "Fay"
                        },
                        new
                        {
                            Id = -7,
                            FirstName = "Alexandra",
                            LastName = "Sporer"
                        },
                        new
                        {
                            Id = -8,
                            FirstName = "Steve",
                            LastName = "Kertzmann"
                        },
                        new
                        {
                            Id = -9,
                            FirstName = "Nicole",
                            LastName = "Rath"
                        },
                        new
                        {
                            Id = -10,
                            FirstName = "John",
                            LastName = "Maggio"
                        });
                });

            modelBuilder.Entity("Migrations.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            City = "Baku",
                            Country = "AZ",
                            UserId = -5
                        });
                });

            modelBuilder.Entity("Migrations.Account", b =>
                {
                    b.HasOne("Migrations.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Migrations.User", b =>
                {
                    b.HasOne("Migrations.UserAddress", "UserAddress")
                        .WithOne("User")
                        .HasForeignKey("Migrations.User", "UserAddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserAddress");
                });

            modelBuilder.Entity("Migrations.User", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("Migrations.UserAddress", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
